# Generated by Django 6.0.3 on 2026-04-06 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('FV', 'Sales invoice'), ('NC', 'Credit note'), ('ND', 'Debit note')], default='FV', max_length=2)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('number', models.IntegerField()),
                ('full_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent to DIAN'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('error', 'Internal error')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.JSONField()),
                ('items', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cufe', models.CharField(blank=True, db_index=True, max_length=200)),
                ('qr_data', models.TextField(blank=True)),
                ('signed_xml', models.TextField(blank=True)),
                ('dian_response', models.JSONField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=300)),
                ('xml_path', models.CharField(blank=True, max_length=300)),
                ('invoice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.certificate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_invoices', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_usage', to='tenants.tenant')),
            ],
            options={
                'db_table': 'monthly_usage',
            },
        ),
        migrations.CreateModel(
            name='RetryQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('exhausted', 'Retries exhausted')], default='pending', max_length=20)),
                ('error_message', models.TextField()),
                ('attempt_number', models.IntegerField()),
                ('next_execution', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='invoices.invoice')),
            ],
            options={
                'db_table': 'retry_queue',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'created_at'], name='invoices_tenant__e4fc29_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='invoices_tenant__14414f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'full_number'], name='invoices_tenant__58567d_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_type', 'prefix', 'number'), name='uq_invoice_number_tenant'),
        ),
        migrations.AddConstraint(
            model_name='monthlyusage',
            constraint=models.UniqueConstraint(fields=('tenant', 'year', 'month'), name='uq_monthly_usage_tenant'),
        ),
        migrations.AddIndex(
            model_name='retryqueue',
            index=models.Index(fields=['status', 'next_execution'], name='retry_queue_status_eec84f_idx'),
        ),
    ]
