# Generated by Django 6.0.3 on 2026-04-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_pdf_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='xml_path',
        ),
    ]
