# Generated by Django 6.0.3 on 2026-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_xml_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_means_code',
            field=models.CharField(default='10', max_length=3),
        ),
    ]
