# Generated by Django 6.0.3 on 2026-05-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_add_payment_means_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver',
            new_name='customer',
        ),
    ]
