# Generated by Django 6.0.3 on 2026-04-06 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('api_key_hash', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='FiscalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=300)),
                ('trade_name', models.CharField(blank=True, max_length=300)),
                ('nit', models.CharField(max_length=20)),
                ('check_digit', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=300)),
                ('city_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=10)),
                ('country_code', models.CharField(default='CO', max_length=3)),
                ('person_type', models.CharField(choices=[('1', 'Legal entity'), ('2', 'Natural person')], max_length=1)),
                ('tax_regime', models.CharField(choices=[('48', 'VAT responsible'), ('49', 'Not VAT responsible')], max_length=2)),
                ('economic_activity', models.CharField(max_length=10)),
                ('tax_responsibilities', models.JSONField(default=list)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10)),
                ('resolution_number', models.CharField(max_length=50)),
                ('resolution_date', models.DateField()),
                ('range_start', models.IntegerField()),
                ('range_end', models.IntegerField()),
                ('current_number', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fiscal_configs',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('p12_encrypted', models.BinaryField()),
                ('password_encrypted', models.CharField(max_length=300)),
                ('expiry_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
