# Generated by Django 6.0.3 on 2026-04-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='ambiente',
            field=models.CharField(choices=[('PRUEBAS', 'Pruebas'), ('PRODUCCIÓN', 'Producción')], default='PRUEBAS', max_length=20),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='clave_tecnica',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_city_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_department_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='resolution_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='software_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='software_pin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='tax_scheme_id',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='tax_scheme_name',
            field=models.CharField(default='IVA', max_length=50),
        ),
    ]
