# Generated by Django 6.0.3 on 2026-04-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_fiscalconfig_ambiente_fiscalconfig_clave_tecnica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]
