# Generated by Django 6.0.3 on 2026-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_certificate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=2)),
                ('department_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=5, unique=True)),
                ('city_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipalities',
                'ordering': ['department_code', 'city_name'],
            },
        ),
    ]
