# Generated by Django 6.0.3 on 2026-04-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_load_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='fiscal_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.municipality', verbose_name='Municipio fiscal'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='registered_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.municipality', verbose_name='Municipio registrado'),
        ),
    ]
