# Generated by Django 6.0.3 on 2026-04-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_municipality_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalconfig',
            name='economic_activity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='trade_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='commercial name'),
        ),
    ]
