# Generated by Django 6.0.3 on 2026-04-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_economic_activity_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalconfig',
            name='economic_activity',
        ),
    ]
