# Generated by Django 6.0.3 on 2026-04-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_remove_economic_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalconfig',
            name='website',
        ),
    ]
