# Generated by Django 6.0.3 on 2026-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalconfig',
            name='tax_scheme_id',
            field=models.CharField(choices=[('01', '01 — IVA (Impuesto sobre las Ventas)'), ('02', '02 — IC (Impuesto al Consumo Departamental Nominal)'), ('03', '03 — ICA (Impuesto de Industria, Comercio y Aviso)'), ('04', '04 — INC (Impuesto Nacional al Consumo)'), ('05', '05 — ReteIVA (Retención sobre el IVA)'), ('06', '06 — ReteRenta (Retención sobre Renta)'), ('07', '07 — ReteICA (Retención sobre el ICA)'), ('08', '08 — IC Porcentual (Impuesto al Consumo Departamental Porcentual)'), ('20', '20 — FtoHorticultura (Cuota de Fomento Hortifrutícula)'), ('21', '21 — Timbre (Impuesto de Timbre)'), ('22', '22 — INC Bolsas (Impuesto Nacional al Consumo de Bolsa Plástica)'), ('23', '23 — INCarbono (Impuesto Nacional del Carbono)'), ('24', '24 — INCombustibles (Impuesto Nacional a los Combustibles)'), ('25', '25 — Sobretasa Combustibles'), ('26', '26 — Sordicom (Contribución minoristas - Combustibles)'), ('30', '30 — IC Datos (Impuesto al Consumo de Datos)'), ('32', '32 — ICL (Impuesto al Consumo de Licores)'), ('33', '33 — INPP (Impuesto nacional productos plásticos)'), ('34', '34 — IBUA (Impuesto a las bebidas ultraprocesadas azucaradas)'), ('35', '35 — ICUI (Impuesto a productos comestibles ultraprocesados)'), ('36', '36 — ADV (Ad Valorem)'), ('ZZ', 'ZZ — Otros tributos, tasas, contribuciones y similares')], default='01', max_length=10),
        ),
    ]
