# Generated by Django 6.0.3 on 2026-04-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tributos_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalconfig',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
