# Generated by Django 6.0.3 on 2026-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_address_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalconfig',
            name='tax_regime',
        ),
    ]
