# Generated by Django 6.0.3 on 2026-04-07 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_remove_tax_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalconfig',
            name='clave_tecnica',
            field=models.CharField(blank=True, default='fc8eac422eba16e22ffd8c6f94b3f40a6e38162c', max_length=200),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='current_number',
            field=models.IntegerField(default=989999999),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='SETP', max_length=10),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='range_end',
            field=models.IntegerField(default=995000000),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='range_start',
            field=models.IntegerField(default=990000000),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='resolution_date',
            field=models.DateField(default=datetime.date(2019, 1, 19)),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='resolution_end_date',
            field=models.DateField(blank=True, default=datetime.date(2030, 1, 19), null=True),
        ),
        migrations.AlterField(
            model_name='fiscalconfig',
            name='resolution_number',
            field=models.CharField(default='18760000001', max_length=50),
        ),
    ]
