# Generated by Django 6.0.3 on 2026-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_resolution_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalconfig',
            name='current_number',
            field=models.IntegerField(default=990000000),
        ),
    ]
