# Generated by Django 6.0.3 on 2026-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_fiscalconfig_current_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalconfig',
            name='test_set_id',
            field=models.CharField(blank=True, help_text='UUID del set de pruebas DIAN. Solo necesario durante habilitación.', max_length=100),
        ),
    ]
