# Generated by Django 6.0.3 on 2026-05-15 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_fiscalconfig_test_set_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='SETP', max_length=10)),
                ('resolution_number', models.CharField(default='18760000001', max_length=50)),
                ('resolution_date', models.DateField(default=datetime.date(2019, 1, 19))),
                ('resolution_end_date', models.DateField(default=datetime.date(2030, 1, 19))),
                ('range_start', models.IntegerField(default=990000000)),
                ('range_end', models.IntegerField(default=995000000)),
                ('clave_tecnica', models.CharField(default='fc8eac422eba16e22ffd8c6f94b3f40a6e38162c', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resolución de pruebas (global)',
                'verbose_name_plural': 'Resolución de pruebas (global)',
                'db_table': 'test_resolution',
            },
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='test_current_number',
            field=models.IntegerField(default=990000000),
        ),
    ]
